task2:
	@echo task2

## task3 desu
## multi line
task3:
	@echo task3

## task1 desu
task1:
	@echo task1

## task4 desuyo
.PHONY: task4
task4:
	@echo task4

## task5 no phony
.DEFAULT: task5
task5:
	@echo task5
